BEHAVE_CATEGORY2NAME = {
    "backpack": "backpack",
    "basketball": "sports ball",
    "boxlarge": "boxlarge",
    "boxlong": "boxlong",
    "boxmedium": "boxmedium",
    "boxsmall": "boxsmall",
    "boxtiny": "boxtiny",
    "chairblack": "chair",
    "chairwood": "chair",
    "keyboard": "keyboard",
    "monitor": "monitor",
    "plasticcontainer": "plasticcontainer",
    "stool": "stool",
    "suitcase": "suitcase",
    "tablesmall": "tablesmall",
    "tablesquare": "tablesquare",
    "toolbox": "toolbox",
    "trashbin": "trashbin",
    "yogaball": "sports ball",
    "yogamat": "yogamat",
}
